"""Reproducible end-to-end intelligence runner for EvidentIQ / HACKMATRIX.

Executes:
  1. Raw Evidence Ingestion & Validation -> scoring/score_engine.py
  2. Longitudinal Trajectory & Confidence Assessment -> trajectory/trajectory_engine.py
  3. AI Coaching Guidance & Evidence Provenance -> recommendation/recommendation_engine.py
  4. Frontend Artifact Sync -> frontend/src/data/mockEmployees.js

Usage:
    python run_pipeline.py
"""

import json
import os
import sys
from pathlib import Path

# Import stages directly
from scoring import score_engine
from trajectory import trajectory_engine
from recommendation import recommendation_engine


def run_full_pipeline(
    raw_input: str = "data/raw_dataset.json",
    scored_out: str = "scored_output.json",
    trajectory_out: str = "trajectory/trajectory_output.json",
    recommendations_out: str = "recommendation/recommendations.json",
    frontend_mock_out: str = "frontend/src/data/mockEmployees.js",
) -> None:
    print("=================================================================")
    print("         EVIDENTIQ - END-TO-END INTELLIGENCE RUNNER              ")
    print("=================================================================")

    # 1. Scoring Engine
    print("\n[Step 1/4] Running Scoring Engine...")
    scored_data = score_engine.run(input_path=raw_input, output_path=scored_out)
    emp_count = len(scored_data.get("employees", []))
    print(f"  -> Validated & scored {emp_count} employees -> {scored_out}")

    # 2. Trajectory Engine
    print("\n[Step 2/4] Running Longitudinal Trajectory & Confidence Engine...")
    traj_data = trajectory_engine.run(input_path=scored_out, output_path=trajectory_out)
    print(f"  -> Evaluated per-competency trajectories & confidence -> {trajectory_out}")

    # 3. AI Recommendation Engine
    print("\n[Step 3/4] Running AI Recommendation & Evidence Grounding Engine...")
    recs_data = recommendation_engine.run(input_path=trajectory_out, output_path=recommendations_out)
    sources = [e["generation_source"] for e in recs_data.get("employees", [])]
    ai_count = sources.count("ai")
    fb_count = sources.count("fallback")
    print(f"  -> Generated {ai_count} AI recommendations and {fb_count} verified fallbacks -> {recommendations_out}")

    # 4. Frontend Data Sync
    print("\n[Step 4/4] Synchronizing Frontend Intelligence Artifacts...")
    traj_js = json.dumps(traj_data, indent=2)
    reco_js = json.dumps(recs_data, indent=2)
    js_content = f"""// Auto-generated by run_pipeline.py
// Full end-to-end intelligence data layer

export const trajectoryData = {traj_js};

export const recommendationsData = {reco_js};
"""
    Path(frontend_mock_out).parent.mkdir(parents=True, exist_ok=True)
    with open(frontend_mock_out, "w", encoding="utf-8") as f:
        f.write(js_content)
    print(f"  -> Synchronized live data to {frontend_mock_out}")

    print("\n=================================================================")
    print(" [OK] End-to-end intelligence pipeline completed successfully!   ")
    print("=================================================================\n")


if __name__ == "__main__":
    run_full_pipeline()
